    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        dest: "/tmp/get_helm.sh"

    - name: Set execute permissions for installation script
      ansible.builtin.file:
        path: "/tmp/get_helm.sh"
        mode: "u+x"

    - name: Check if Helm is installed
      ansible.builtin.command: helm version --client
      register: helm_check
      ignore_errors: true
      changed_when: false
      become: false


    - name: Execute Helm installation script
      ansible.builtin.command: "/tmp/get_helm.sh"
      when: helm_check.rc != 0
      become: false