
    - name: Create directory for Terraform versions
      file:
        path: "{{ terraform_install_dir }}"
        state: directory

    - name: Download Terraform binaries
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ item }}/terraform_{{ item }}_linux_amd64.zip"
        dest: "{{ terraform_install_dir }}/terraform_{{ item }}.zip"
      loop: "{{ terraform_versions }}"
    
    - name: Extract Terraform binaries
      ansible.builtin.unarchive:
        src: "{{ terraform_install_dir }}/terraform_{{ item }}.zip"
        dest: "{{ terraform_install_dir }}"
        remote_src: yes
        creates: "{{ terraform_install_dir }}/terraform_{{ item }}"
      loop: "{{ terraform_versions }}"

    - name: Set symlink for active Terraform version
      file:
        src: "{{ terraform_install_dir }}/terraform_{{ active_terraform_version }}"
        dest: "/usr/local/bin/terraform"
        state: link

# terraform docs

    - name: Download terraform-docs
      ansible.builtin.get_url:
        url: "https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-{{ ansible_system }}-amd64.tar.gz"
        dest: "/tmp/terraform-docs.tar.gz"

    - name: Extract terraform-docs
      ansible.builtin.unarchive:
        src: "/tmp/terraform-docs.tar.gz"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/terraform-docs"

    - name: Set execute permissions for terraform-docs
      ansible.builtin.file:
        path: "/tmp/terraform-docs"
        mode: "0755"

    - name: Move terraform-docs to a directory in PATH
      ansible.builtin.command: "mv /tmp/terraform-docs /usr/local/bin/terraform-docs"

