
    - name: Create directory for Terraform versions
      file:
        path: "{{ terraform_install_dir }}"
        state: directory

    - name: Download Terraform binaries
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ item }}/terraform_{{ item }}_linux_amd64.zip"
        dest: "{{ terraform_install_dir }}/terraform_{{ item }}.zip"
      loop: "{{ terraform_versions }}"
    
    - name: Extract Terraform binaries
      ansible.builtin.unarchive:
        src: "{{ terraform_install_dir }}/terraform_{{ item }}.zip"
        dest: "{{ terraform_install_dir }}_{{ item }"
        remote_src: yes
        creates: "{{ terraform_install_dir }}/terraform_{{ item }}"
      loop: "{{ terraform_versions }}"

    - name: Set symlink for active Terraform version
      file:
        src: "{{ terraform_install_dir }}/terraform_{{ active_terraform_version }}"
        dest: "/usr/local/bin/terraform"
        state: link

