software_to_install:
  - tree
  - aws-cli
  - git
  - jq
  - curl
  - wget
  - nmap-ncat
  - unzip
  - net-tools
  - yum-utils
  - shadow-utils

terraform_versions:
  - 1.8.0
  - 1.7.0
  - 1.6.0
  - 1.5.0
  - 1.4.0
  - 1.3.0
  - 1.2.0
  - 1.1.0
  - 1.0.0

vscode_extentions:
  - golang.go
  - hashicorp.terraform

terraform_install_dir: "/opt/terraform-versions"
active_terraform_version: "1.8.0"  

vault_version: "1.16.2"
vault_install_dir: "/opt/vault"